### ISSUE TITLE
Doesn't work with int.

### ISSUE THREAD

**Issue by pjebs** [Jeffail/gabs#12]
For this json:
`
{
"login":{
    "service":99,
    "id":"12345"
    },
"me":{
        "name": "ABC DEF"
    }
}
`

`
id_service, ok_1 := reqJson.Path("login.service").Data().(int)
`

ok_1 returns false.
If I change 99 to be a string, and change the type assertion it works.

**Comment by pjebs** [comment]
It seems to work if I change `.(int)` to `.(float64)`.
Not sure if this is the intended behaviour. Feel free to close if it is.

**Comment by Jeffail** [comment]
Hey @pjebs,

This is because gabs uses the standard golang JSON package for parsing bytes, which by default will parse all numbers into floats. Take a look [at this issue](https://github.com/Jeffail/gabs/issues/6) for more explanation and a work around.

You are currently the second vocal person to be adversely effected by this, so no doubt this has effected others as well and should be looked at. I'll flag this as a bug and try and think of a nice solution, suggestions are welcome in the meantime.

**Comment by danielnitz** [comment]
I just wasted 30 mins on this as well

**Comment by jinleileiking** [comment]
I have cost 2 hour in this stupid question...

PLEASE ADD THIS IN README, COMMONLY USE INT NOT USE FLOAT64

PLEASE ADD THIS IN README, COMMONLY USE INT NOT USE FLOAT64


PLEASE ADD THIS IN README, COMMONLY USE INT NOT USE FLOAT64



WTF!!!

**Comment by sairam** [comment]
Since Data() is an interface{}, the responsibility scope is assumed outside the library.

See http://stackoverflow.com/a/29690346/208928 

```go
var iAreaId int = int(val.(float64))
```
