### ISSUE TITLE
High memory usage compared to node.js

### ISSUE THREAD

**Issue by tobias-zeptio** [Jeffail/gabs#144]
I'm quite new to go, and particulary new to go in a high demand production environment. But I've used it for simpler application, and I've happy with the work flow.

Now my team has migrated a in-memory writethrough cache that we have in front of a hosted mongodb database. The previous version of the cache was writen in node.js because the data we keep is highly dynamic and javascript is really easy to use for that. But not surprising we have had issues with inconsistent latency because of it being single threaded.

Looking into migrating to go I found this library, and it made the move so easy. Thank you! But, after deploying this to production I noticed that the memory usage is alot higher. In node we stored our cache in plain objects, and used "reflection" to set and get values. One instance used about 1,5 GB for 50 000 objects, for go and this library we get 10 GB for 50 000 objects. Is this normal and expected as a difference in memory usage between node and go, or could it be that we are using the library incorrectly?

The mongodb driver fetched data from the database using bson, and it needs to be marshalled to a map[string]interface{} that we then store in a gabs container. 

go mongodb code (error handling removed)
```
	var result bson.D
	_ := c.collection.FindOne(ctx, bson.M{"_id": iprId}, opts).Decode(&result)

	var temp, _ = bson.MarshalExtJSON(result, false, false)

	var device map[string]interface{}
	err = json.Unmarshal(temp, &device)

	return device, nil
```

this is then used to set the root value in the gabs container (simplified)

```
container := gabs.New()
container.Set(device)
```

I'm sorry if this is the wrong place to ask this, but I assume that the people maintaning this would be knowledgable and maybe even interested in this use case.

**Comment by mihaitodor** [comment]
Hey @tobias-zeptio 👋 Thanks for trying out Gabs! It's not really possible to say what might be consuming so much memory without looking at a memory profile in pprof. The partial code you shared there seems pretty trivial and Gabs doesn't really hold any global cache as far as I know (feel free to look through the code since it's pretty straightforward).

**Comment by tobias-zeptio** [comment]
Yeah, I realized I should have attached the pprof heap. So here it is. 
[main inuse_space.pdf](https://github.com/user-attachments/files/17374611/main.inuse_space.pdf)

Noticable to me here is that the heap memory is about half of what is reported by the metrics-server in kubernetes. 4982 MB vs 10145 MB. And that all the memory is under this "json" scope. Is that what's stored in gabs?

And I forgot to say, one device is around 8 KB in json. So best case storing these 50000 devices in memory would be 400 MB. How much overhead would you guess go or gabs adds to storing a map[string]interface{} of that size? I'm trying to figure out if this is reasonable, or if I'm doing something wrong here.

**Comment by tobias-zeptio** [comment]
I've looked into to code some, but it seems pretty straight forward. And because it handle interface{} I assume gabs doesn't manage the data structure directly. Or am I misunderstanding this, how much control do I have over the underlying data structures of what I put into a gabs container? Is this json.valueInterface expected to be the main memory holder on the heap? Coming from node, I expected the heap to say map[string]interface{} or something. Or be more hierarchical and not just one json.valueInteraface blob.

**Comment by mihaitodor** [comment]
I see. The `encoding/json` library is suboptimal in various ways. I'd try testing a fork of Gabs which uses https://github.com/goccy/go-json for example (there are others as well). Another issue is that Go only recently released the [`unique` package](https://pkg.go.dev/unique) (see this [blog post](https://go.dev/blog/unique)) and I assume that NodeJS might be using a similar technique already if its memory footprint is much lower. There's also https://github.com/go-json-experiment/json which will eventually become `encoding/json/v2`, but it's not finished yet and it might require a few code changes to get Gabs to use it. Maybe worth trying that out as well.

Otherwise, I saw some references to MongoDB in that heap profile, but dunno if that has anything to do with the issue you're seeing. Just wondering if maybe the MongoDB libraries are caching stuff too much internally.

**Comment by tobias-zeptio** [comment]
After more testing I have concluded that it's the map[string]interface{} type that is so memory inefficient. Storing the JSON as []byte uses 1/20 of the memory.

Our JSON structure is heavily nested and I need to look into flattening the structure somehow. Thank you for a great library! :)
