### ISSUE TITLE
question

### ISSUE THREAD

**Issue by alphacentory** [Jeffail/gabs#26]
do you have anymore performance tests? 
I am looking at using this in a opensource OAI project. Just want to compare to other packages.

**Comment by Jeffail** [comment]
Hey @BafFlynN. Sorry, this issue slipped out of my radar. 

Gabs will likely be one of the slowest libraries since it not only wraps `json.Unmarshal` but also uses `interface{}` (and therefore reflection) a lot. If you are able to define your JSON structures as Golang `struct` types at compile time then your best bet is anything other than Gabs. This library comes in handy when your JSON paths and structures aren't defined until runtime, as it has a simple API for extracting and editing paths that can be determined and resolved dynamically.
